Bring back permanent `/opt/tinypilot-updater` folder
tiny-pilot/tinypilot pull request #1065
Opened 2022-07-21 12:29 UTC by jotaen4tinypilot

Resolves https://github.com/tiny-pilot/ansible-role-tinypilot/issues/206.

As discussed in the ticket, we bring back the permanent `/opt/tinypilot-updater` folder, to stay backwards compatible with code that still relies on that path. I also had to “revert” the recent [`venv`-related changes](https://github.com/tiny-pilot/tinypilot/pull/1059), because in order for the privileged scripts to run the ansible roles, [they expect the `venv` folder to exist](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/14cc40e7e53260628be09597799533e080bfc7f9/files/update-video-settings#L57-L60).

With the changes from this branch, I was able to produce a TinyPilot installation on a fresh device with functioning video settings.

2022-07-21 13:07 UTC, jdeanwallace requested changes
##### Automated comment from CodeApprove ([go to review](https://codeapprove.com/pr/tiny-pilot/tinypilot/1065))



<hr />

In: **Dockerfile**:

```
> Line 55
  rm -rf /opt/tinypilot
```
Based on [Michael's comment here](https://github.com/tiny-pilot/ansible-role-tinypilot/issues/206#issuecomment-1190454448), we should always remove `/opt/tinypilot-updater`.

> ... we have to unconditionally remove `/opt/tinypilot-updater` in `prerm` to prevent stale files from being left behind across versions.

<hr />

In: **get-tinypilot.sh**:

```
> Line 89
mkdir -p "${INSTALLER_DIR}"
```
Can we update/replace the installer-directory in an atomic way?

For example, keep the temporary bundle-directory and only replace the `/opt/tinypilot-updater` path after the installation has succeeded.

This would also prevent the Debian package from removing the `/opt/tinypilot-updater` directory when running `prerm` as part of its [package upgrade process](https://www.debian.org/doc/debian-policy/ch-maintainerscripts.html#summary-of-ways-maintainer-scripts-are-called). 

This comment is also related to the one below.


<hr />

👀 @jotaen4tinypilot it's your turn please take a look

2022-07-21 13:40 UTC, jotaen4tinypilot reviewed
##### Automated comment from CodeApprove ([go to review](https://codeapprove.com/pr/tiny-pilot/tinypilot/1065))



<hr />

In: **Dockerfile**:

```
> Line 55
  rm -rf /opt/tinypilot
```
My assumption was that we originally wanted to remove the `/opt/tinypilot-updater` path in `preinst` in order to clean up the system when migrating to the new update behaviour.

I’m not sure we should still touch the `/opt/tinypilot-updater` folder from within the Debian package, now that we are about to bring it back permanently. My thinking is that the Debian package doesn’t actually know anything about the existence of that folder, so it could be risky to have different parts of the installation process independently remove and create the folder. I.e., the Debian package *removes* the `/opt/tinypilot-updater` folder, but it’s not responsible to create it. I’d be worried that this indirection could create complications. So I thought it might be more straightforward to let `get-tinypilot.sh` deal with `/opt/tinypilot-updater`, and the Debian package with `/opt/tinypilot`.

I might be missing something here, though.

<hr />

In: **get-tinypilot.sh**:

```
> Line 89
mkdir -p "${INSTALLER_DIR}"
```
I’d see a slight benefit in copying the `/opt/tinypilot-updater` folder early in the process. We need to persist it anyway, so by saving it in the eventual location right away, we eliminate the possibility that the folder isn’t copied due to a potential error earlier in the installation process. It’d also resemble the original behaviour more closely, where we [pulled and persisted the new code first and then executed it](https://github.com/tiny-pilot/tinypilot/blob/cc697a69afcb1ca919085308b070903d501dbb51/quick-install#L170-L173).

I don’t feel super strongly about it, though, and as mentioned above, I might not consider something here.


<hr />

👀 @jdeanwallace it's your turn please take a look

2022-07-21 19:30 UTC, mtlynch reviewed
##### Automated comment from CodeApprove ([go to review](https://codeapprove.com/pr/tiny-pilot/tinypilot/1065))



<hr />

In: **Dockerfile**:

```
> Line 55
  rm -rf /opt/tinypilot
```
Yeah, I agree with Jan. I hadn't thought about the inconsistency of the Debian package removing `/opt/tinypilot-updater` but not placing it.

The downside is that it gets left behind after uninstall, but that's not such a big deal.


<hr />

👀 @jdeanwallace it's your turn please take a look

2022-07-22 11:36 UTC, jdeanwallace requested changes
##### Automated comment from CodeApprove ([go to review](https://codeapprove.com/pr/tiny-pilot/tinypilot/1065))


✔️ Approved (2 unresolved comments)

<hr />

In: **get-tinypilot.sh**:

```
> Line 89
mkdir -p "${INSTALLER_DIR}"
```
> It’d also resemble the original behaviour more closely

Good point, thanks.

<hr />

In: **get-tinypilot.sh**:

```
> Line 87
# Extract tarball to temporary directory and run install.
```
Can we correct this comment by replacing "temporary" with "installer"?

<hr />

In: **get-tinypilot.sh**:

```
> Line 88
rm -rf "${INSTALLER_DIR}"
```
Can we use `sudo` when removing and creating the installer-dir? I'm getting a permission denied error here.
Based on [original behaviour we should also probably change ownership too](https://github.com/tiny-pilot/tinypilot/blob/cc697a69afcb1ca919085308b070903d501dbb51/quick-install#L143-L145).


<hr />

👀 @jotaen4tinypilot it's your turn please take a look

2022-07-22 16:44 UTC, jotaen4tinypilot reviewed
##### Automated comment from CodeApprove ([go to review](https://codeapprove.com/pr/tiny-pilot/tinypilot/1065))



<hr />

In: **get-tinypilot.sh**:
Ah, thanks for noticing this! Fixed.

<hr />

In: **get-tinypilot.sh**:
Done. I’ve also added a comment above the `$INSTALLER_DIR` declaration, to preserve some context why we do this to begin with.

2022-07-22 16:44 UTC, jdeanwallace approved these changes
##### Automated comment from CodeApprove ([go to review](https://codeapprove.com/pr/tiny-pilot/tinypilot/1065))

Approved: I have approved this change on CodeApprove and all of my comments have been resolved.

2022-07-22 16:47 UTC, merged