Add smoke test for bundle integrity.
tiny-pilot/tinypilot pull request #1066
Opened 2022-07-22 13:39 UTC by jdeanwallace

Resolves https://github.com/tiny-pilot/tinypilot/issues/1006

2022-07-22 14:01 UTC, jdeanwallace commented
##### Automated comment from CodeApprove ([go to review](https://codeapprove.com/pr/tiny-pilot/tinypilot/1066))

⏳ @jotaen4tinypilot please review this Pull Request

2022-07-22 15:07 UTC, jotaen4tinypilot requested changes
##### Automated comment from CodeApprove ([go to review](https://codeapprove.com/pr/tiny-pilot/tinypilot/1066))


✔️ Approved (1 unresolved comments)

The check procedure looks good to me 👍

My only (optional) thought would be, whether we want to put the code into a dedicated bash script, e.g. at `/bundler/check-bundle-integrity` or `/bundler/verify-bundle`? I’d probably find that slightly more manageable than having the bash code all inside the YAML file.

<hr />

In: **.circleci/config.yml**:

```
> Line 186
            for ANSIBLE_ROLE in "${ANSIBLE_ROLES[@]}"; do
```
Nit: I think `ANSIBLE_ROLE` can be lower-case, since it’s a “local” variable. (See [code sample here](https://google.github.io/styleguide/shellguide.html#s5.4-loops))


<hr />

👀 @jdeanwallace it's your turn please take a look

2022-07-25 12:07 UTC, jdeanwallace reviewed
##### Automated comment from CodeApprove ([go to review](https://codeapprove.com/pr/tiny-pilot/tinypilot/1066))



<hr />

In: **Discussion**
Good idea, I've added a `bundler/verify-bundle` script to live alongside the `bundler/create-bundle` script. It didn't feel right to place it the `dev-scripts/` directory.

I've tested the `verify-bundle` script in CircleCI here:
https://app.circleci.com/pipelines/github/tiny-pilot/tinypilot/2381/workflows/c457680c-0c44-4959-82d9-02d385f04e75

<hr />

In: **.circleci/config.yml**:
Done.


<hr />

👀 @jotaen4tinypilot it's your turn please take a look

2022-07-25 17:09 UTC, jotaen4tinypilot approved these changes
##### Automated comment from CodeApprove ([go to review](https://codeapprove.com/pr/tiny-pilot/tinypilot/1066))



<hr />

In: **Discussion**
👍 


<hr />

👀 @jdeanwallace it's your turn please take a look

2022-07-26 11:18 UTC, merged