Status bar: add indicator for streaming mode
tiny-pilot/tinypilot pull request #1181
Opened 2022-11-04 15:45 UTC by jotaen4tinypilot

Resolves https://github.com/tiny-pilot/tinypilot/issues/1144 (POC/discussion here: https://github.com/tiny-pilot/tinypilot/pull/1175), stacked onto https://github.com/tiny-pilot/tinypilot/pull/1180.

<img width="569" alt="Screenshot 2022-11-04 at 16 33 24" src="https://user-images.githubusercontent.com/83721279/200015020-3c005f72-31c0-4209-bbda-2a611c40ea9a.png">

Notes:

- Similar to [how the `<video-settings>` dialog does it](https://github.com/tiny-pilot/tinypilot/blob/ae966c96cfd3a4f5a2fccf9e0c16b24f5fc6fb2f/app/templates/custom-elements/video-settings-dialog.html#L98-L106), I would differentiate between streaming mode’s internal, technical name, and the display value. For `MJPEG` it happens to be the same, but [for `H264` we want to display it as `H.264`](https://github.com/tiny-pilot/tinypilot/pull/1176). Since this is presentational logic, I think it makes most sense to have that in the UI component, even at the expense of some LOC/verbosity.
- Initializing the remote screen has to happen in `app.js` now, otherwise the `VideoStreamingModeChangedEvent` will be emitted before all event handlers are wired up, so the initial event just vanishes.
- The font-size of the label (`MJPEG`/`H.264`) is slightly reduced, otherwise it appears as “too big”, since it’s all-caps.
<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1181"><img src="https://codeapprove.com/external/github-tag-allbg.png" alt="Review on CodeApprove" /></a>

2022-11-04 16:28 UTC, mtlynch submitted a review, later dismissed
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1181)



<hr />

In: **app/templates/custom-elements/video-stream-indicator.html**:

```
> Line 61
  <div class="status-bar-tooltip">
```
(very optional, just an idea) What if instead of "You can change the streaming mode..." we say "Click to change the streaming mode." and have it fire the "open video settings dialog" event?

I'm not sure about it as it's outside our normal UI conventions, but it's easier for the user. It also avoids the pitfall where we might forget to update this UI text if we change the way the user accesses the Video Settings dialog.

<hr />

In: **app/templates/custom-elements/video-stream-indicator.html**:

```
> Line 65
    compression to stream the video output of your target device. You can
```
This feels a bit bulky in the tooltip as a single paragraph. What do you think of adding `<br><br>` before "You can" (or using `<p>` tags).

<hr />

In: **app/templates/custom-elements/video-stream-indicator.html**:

```
> Line 66
    configure the streaming mode in the “System” > “Video Settings” dialog.
```
I want to make sure the > is always on a single line, so can we use `&nbsp;`. Also, I think we don't want to have an unescaped angle bracket, so suggest:

```
&nbsp;&gt;&nbsp;
```


<hr />

👀 @jotaen4tinypilot it's your turn please take a look

2022-11-07 18:25 UTC, mtlynch commented
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1181)

⏳ @jdeanwallace please review this Pull Request

2022-11-07 18:27 UTC, mtlynch requested changes
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1181)



<hr />

In: **Discussion**
Re-assigning to @jdeanwallace for the full review.

One issue I noticed is that on Windows+FF, I see a large empty space on the right side:


![image.png](https://firebasestorage.googleapis.com/v0/b/codeapprove-prod.appspot.com/o/MTY2Nzg0NTYxNjM4My1pbWFnZS5wbmc.png?alt=media&token=0a0fc61e-9b2b-4bc1-9291-21e424cb98b7) 


It's not a major issue, but it'd be good to fix this if it's easy.


<hr />

👀 @jdeanwallace, @jotaen4tinypilot it's your turn please take a look

2022-11-08 11:55 UTC, jdeanwallace requested changes
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1181)


⏳ Approval Pending (2 unresolved comments)
_Approval will be granted automatically when all comments are resolved_

<hr />

In: **Discussion**
Some possibly confusing behaviour with regards to the stream falling back to MJPEG. The indicator tells me that the current streaming mode is MJPEG, but when I look at the "System" > "Video Settings", it tells me that H264 is in fact enabled. So as a user I'm confused on why H264 is not working.

[Screen Recording 2022-11-08 at 13.38.04.mov](https://firebasestorage.googleapis.com/v0/b/codeapprove-prod.appspot.com/o/MTY2NzkwODE5MDI0MS1TY3JlZW4gUmVjb3JkaW5nIDIwMjItMTEtMDggYXQgMTMuMzguMDQubW92.mov?alt=media&token=f119fe7d-5210-4763-8573-3f7ba09adbf5) 

Off the top of my head, it would be cool to show that h264 was attempted but failed. Something like this maybe 😅

![Screen Shot 2022-11-08 at 13.48.57.png](https://firebasestorage.googleapis.com/v0/b/codeapprove-prod.appspot.com/o/MTY2NzkwODI3NDY3NS1TY3JlZW4gU2hvdCAyMDIyLTExLTA4IGF0IDEzLjQ4LjU3LnBuZw.png?alt=media&token=ea0f656e-1520-49f6-b90e-37fddb8a89ea) 


<hr />

In: **app/templates/custom-elements/video-stream-indicator.html**:

```
> Line 39
  <svg class="icon" viewBox="0 0 500 416" xmlns="http://www.w3.org/2000/svg">
```
Could we move the svg to its own file under `app/static/img/`? The svg takes a lot of space that I would never edit in code.


<hr />

👀 @jotaen4tinypilot, @mtlynch it's your turn please take a look

2022-11-08 12:04 UTC, mtlynch reviewed
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1181)



<hr />

In: **app/templates/custom-elements/video-stream-indicator.html**:

```
> Line 39
  <svg class="icon" viewBox="0 0 500 416" xmlns="http://www.w3.org/2000/svg">
```
In general, I think we should inline SVGs if we're only using them once unless they're so large (100+ LOC) that they dominate the file. I think there are performance implications, but I'm not concerned about that. But with a separate file, we run the risk of orphaning the file if we delete the reference, which would be harder to do with inline SVG.

I don't feel super strongly about this, so I'm open to whatever you both prefer if you have stronger preferences.


<hr />

👀 @jdeanwallace, @jotaen4tinypilot it's your turn please take a look

2022-11-08 15:27 UTC, jdeanwallace approved these changes
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1181)

Approved: I have approved this change on CodeApprove and all of my comments have been resolved.

2022-11-08 15:34 UTC, merged