Fix Debian package filename to use arch all instead of armhf
tiny-pilot/tinypilot pull request #1197
Opened 2022-11-15 16:44 UTC by mtlynch

We have a mismatch between the architecture we declare in the Debian package and the architecture we specify in the filename. The filename was specifying an architecture of armhf, while the Debian package was declaring all. all is correct, so this change updates the filename to match and makes it harder for the two to go out of sync.

2022-11-15 16:44 UTC, mtlynch commented
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1197)

⏳ @jdeanwallace please review this Pull Request

2022-11-16 13:18 UTC, jdeanwallace requested changes
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1197)


⏳ Approval Pending (1 unresolved comments)
_Approval will be granted automatically when all comments are resolved_

<hr />

In: **debian-pkg/Dockerfile**:

```
> Line 25
ARG PKG_ARCH="all"
```
Is this still true seeing that we always try to install janus [which has a `armhf` architecture](https://github.com/tiny-pilot/janus-debian/blob/997e41348238015f0ab9f0c4c8843f2a07c796c6/Dockerfile#L10)?



<hr />

👀 @mtlynch it's your turn please take a look

2022-11-16 13:27 UTC, mtlynch reviewed
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1197)



<hr />

In: **debian-pkg/Dockerfile**:

```
> Line 25
ARG PKG_ARCH="all"
```
Yep, this is just declaring the architecture of the current package. If there are no matching armhf binaries for our dependencies, Debian will complain at install time, but this package is architecture-agnostic.

2022-11-16 13:27 UTC, jdeanwallace approved these changes
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1197)

Approved: I have approved this change on CodeApprove and all of my comments have been resolved.

2022-11-16 13:29 UTC, merged