Add HID Keystroke class
tiny-pilot/tinypilot pull request #1629
Opened 2023-09-18 10:46 UTC by jdeanwallace

Related https://github.com/tiny-pilot/tinypilot/issues/1026

This PR introduces the HID `Keystroke` class that represents a combination of HID keycode and HID modifier. This PR replaces the use of individual `keycode` and `modifier`/`control_keys` variables with a single `keystroke` variable.

This is a non-functional change that simplifies the way we represent HID Keystrokes in anticipation for parsing text to HID keystrokes via https://github.com/tiny-pilot/tinypilot/pull/1624

### Notes:
1. In https://github.com/tiny-pilot/tinypilot/pull/1625, we parse `text` + `language` directly to HID keystrokes in a [`request_parser`](https://github.com/tiny-pilot/tinypilot/blob/df246c830564eb164b9206d9ea9b0cfc6ae4e248/app/request_parsers/paste.py#L6-L44). Ideally, I'd like to do the same when [parsing JS keystroke WebSocket messages](https://github.com/tiny-pilot/tinypilot/blob/60fe150efe22bc5dfd6c328c841d109288a72274/app/request_parsers/keystroke.py#L40-L58) which are [polluting `socket_api.py` with JS-to-HID conversion logic](https://github.com/tiny-pilot/tinypilot/blob/60fe150efe22bc5dfd6c328c841d109288a72274/app/socket_api.py#L23-L33). This kind of change would cause some churn, so I did not implement that here.

2023-09-18 11:09 UTC, jdeanwallace commented
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1629)

⏳ @mtlynch please review this Pull Request

2023-09-18 11:44 UTC, mtlynch requested changes
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1629)


⏳ Approval Pending (1 unresolved comments)
_Approval will be granted automatically when all comments are resolved_

LGTM, thanks!

<hr />

In: **Discussion**
>I think I found a piece of dead-code. From what I understand, this if statement can never be truthy 🤔

Yeah, let's drop that. Can we also document `js_to_hid` to document that `convert` either returns a valid `Keystroke` or raises an exception?


<hr />

👀 @jdeanwallace it's your turn please take a look

2023-09-18 12:20 UTC, jdeanwallace reviewed
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1629)



<hr />

In: **Discussion**
Done.

2023-09-18 12:20 UTC, mtlynch approved these changes
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1629)

Approved: I have approved this change on CodeApprove and all of my comments have been resolved.

2023-09-18 13:02 UTC, mtlynch submitted a review, later dismissed
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1629)


⏳ Approval Pending (1 unresolved comments)
_Approval will be granted automatically when all comments are resolved_

<hr />

In: **app/js_to_hid.py**:

```
> Line 159
    Returns:
```
Can we reorder this so Raises is last?

https://google.github.io/styleguide/pyguide.html#244-decision


<hr />

👀 @jdeanwallace it's your turn please take a look

2023-09-19 10:26 UTC, jdeanwallace reviewed
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1629)



<hr />

In: **app/js_to_hid.py**:
Thanks. Done.

2023-09-19 10:26 UTC, mtlynch approved these changes
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1629)

Approved: I have approved this change on CodeApprove and all of my comments have been resolved.

2023-09-19 10:27 UTC, merged