Revise bug template for better feedback
tiny-pilot/tinypilot pull request #1740
Opened 2024-02-07 15:27 UTC by db39

Resolves #1732 

This change fixes the command for collecting a log, adds instructions for retrieving a log on the TinyPilot web interface, and adds a section asking for video capture hardware (if applicable).

2024-02-07 15:32 UTC, db39 commented
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1740)

⏳ @cghague please review this Pull Request

2024-02-08 00:18 UTC, cghague requested changes
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1740)



<hr />

In: **.github/ISSUE_TEMPLATE/bug_report.md**:

```
> Line 33
If your issue relates to video capture, please report which HDMI capture device you're using, e.g., "MacroSilicon MS2109 HDMI to USB". You can refer to the [wiki](https://github.com/tiny-pilot/tinypilot/wiki/HDMI-Capture-Devices) if you're unsure.
```
I'm not keen on the Markdown hyperlink since most people will only see the template in the "raw" format. I suggest dropping the `You can...` sentence and instead putting the URL on a separate line.

<hr />

In: **.github/ISSUE_TEMPLATE/bug_report.md**:

```
> Line 37
Please share a TinyPilot log for review.
```
Suggest `Please share a link to a TinyPilot log for review.`. This change should clarify that we want a link, not the log contents.

<hr />

In: **.github/ISSUE_TEMPLATE/bug_report.md**:

```
> Line 39
If you have access to the TinyPilot web interface, navigate to _System > Logs_ in the menu and click _Get Shareable URL_. Please paste the URL: `https://logs.tinypilotkvm.com/...`
```
Can we just ask the user to paste the URL from the clipboard rather than giving a partial example?


<hr />

👀 @db39 it's your turn please take a look

2024-02-08 12:28 UTC, db39 reviewed
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1740)



<hr />

In: **.github/ISSUE_TEMPLATE/bug_report.md**:
Resolved

<hr />

In: **.github/ISSUE_TEMPLATE/bug_report.md**:
Resolved

<hr />

In: **.github/ISSUE_TEMPLATE/bug_report.md**:
Yeah, looking again, the Markdown hyperlink looks awkward. Having the URL on a separate line without context / instructions seems a bit odd. So I've re-written the sentence and added the plaintext URL at the end - I think that makes it clearer why the URL is there and it doesn't look weird like the Markdown hyperlink.


<hr />

👀 @cghague it's your turn please take a look

2024-02-08 16:40 UTC, cghague approved these changes
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1740)


<a href="https://codeapprove.com/pr/tiny-pilot/tinypilot/1740"><img src="https://codeapprove.com/external/github-stamp-allbg.png" width="159" alt="Approved on CodeApprove" /></a>
✔️ Approved

LGTM

<hr />

👀 @db39 it's your turn please take a look

2024-02-09 21:02 UTC, mtlynch submitted a review, later dismissed
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1740)


⏳ Approval Pending (3 unresolved comments)
_Approval will be granted automatically when all comments are resolved_

LGTM, thanks!

<hr />

In: **.github/ISSUE_TEMPLATE/bug_report.md**:

```
> Line 33
If your issue relates to video capture, please report which HDMI capture device you're using, e.g., "MacroSilicon MS2109 HDMI to USB". Refer to the capture device wiki if you're unsure: https://github.com/tiny-pilot/tinypilot/wiki/HDMI-Capture-Devices
```
>you're using, e.g., "MacroSilicon MS2109 HDMI to USB". 

Should be:

>you're using (e.g., "MacroSilicon MS2109 HDMI to USB").

<hr />

In: **.github/ISSUE_TEMPLATE/bug_report.md**:

```
> Line 39
If you have access to the TinyPilot web interface, navigate to _System > Logs_ in the menu and click _Get Shareable URL_ to copy the URL. Please paste the URL.
```
I think we can drop "Please paste the URL," since they'll probably assume that part.

I know we're trying to discourage users from dumping their whole log, but I don't think that sentence will really move the needle. I think the rest of the guidance does a good job already of guiding them toward sharing the URL rather than the log itself.

<hr />

In: **.github/ISSUE_TEMPLATE/bug_report.md**:

```
> Line 41
If you don't have access to the TinyPilot web interface, please share the URL you see when you run `sudo /opt/tinypilot-privileged/collect-debug-logs`
```
I think @cghague made a good point earlier when he pointed out that users will see this in raw markdown format when they file the bugs.

With that in mind, I think it makes more sense to put the command on its own line in triple backticks so that it's easier to copy/paste. With inline backticks, they have to be very precise with selecting characters.


<hr />

👀 @db39 it's your turn please take a look

2024-02-13 11:22 UTC, db39 reviewed
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1740)



<hr />

In: **.github/ISSUE_TEMPLATE/bug_report.md**:
Resolved

<hr />

In: **.github/ISSUE_TEMPLATE/bug_report.md**:
Resolved

<hr />

In: **.github/ISSUE_TEMPLATE/bug_report.md**:
Resolved

2024-02-13 11:22 UTC, mtlynch approved these changes
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1740)

Approved: I have approved this change on CodeApprove and all of my comments have been resolved.

2024-02-13 11:22 UTC, merged