Define standard CircleCI executors
tiny-pilot/tinypilot pull request #1750
Opened 2024-03-08 14:18 UTC by jdeanwallace

Related https://github.com/tiny-pilot/tinypilot-pro/issues/1229

In an effort to reduce repetition on our CircleCI config, this PR defines standard CircleCI `executors` instead of redefining them on every job.

Notes:
1. CircleCI's `cimg/base` is an Ubuntu image:
    > `cimg/base` is an Ubuntu Docker image created by CircleCI with continuous integration builds in mind. As its name suggests, this image is designed to serve as a base image for other CircleCI Convenience Images (images prefixed with cimg/).
1. This means that most jobs would use the same base image and are now being upgraded to the latest available image (i.e., `cimg/base:2024.02`)

2024-03-08 14:22 UTC, jdeanwallace commented
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1750)

⏳ @jotaen4tinypilot please review this Pull Request

2024-03-08 21:12 UTC, mtlynch commented
Oh, neat! I didn't know about this. I need to go refactor like 50 repos now.

>This means that most jobs would use the same base image and are now being upgraded to the latest available image (i.e., cimg/base:2024.02) We can't upgrade the base images on all jobs because some rely on very specific versions.

Does that job actually rely on that specific image or did we just give it an overly specific tag back when we created it? If it specifically depends on that exact tag, can we add a comment in this PR explaining why?

2024-03-10 08:20 UTC, jdeanwallace commented
@mtlynch 

> I need to go refactor like 50 repos now.

My pleasure! 😁 

> Does that job actually rely on that specific image...

Good question 🤔 I think we made it that specific ubuntu image version back in the day because we wanted at least `lintian=2.114.0ubuntu1`, but now the new ubuntu image can install [newer lintian versions](https://launchpad.net/ubuntu/+source/lintian) anyway. So yay, we can upgrade all base images 🙌

2024-03-11 11:45 UTC, mtlynch requested changes
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1750)



<hr />

In: **.circleci/config.yml**:

```
> Line 183
          command: sudo apt-get install -y lintian
```
With linters, we generally want them pinned to an exact version. Otherwise, the linter can update out from under us and start flagging a new issue, and our build breaks even though we haven't changed anything.

We don't have to keep the lintian version `2.114.0ubuntu1`, but it should be a specific version so that it can't update to something else out from under us.


<hr />

👀 @jdeanwallace, @jotaen4tinypilot it's your turn please take a look

2024-03-11 12:29 UTC, jdeanwallace reviewed
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1750)



<hr />

In: **.circleci/config.yml**:
Ah right, thanks. I've preserved the lintian version pin to `2.114.0ubuntu1` (just because we know it works).


<hr />

👀 @jotaen4tinypilot, @mtlynch it's your turn please take a look

2024-03-11 13:41 UTC, merged