Allow for extra Playwright CLI options.
tiny-pilot/tinypilot pull request #1768
Opened 2024-03-31 13:58 UTC by jdeanwallace

Resolves https://github.com/tiny-pilot/tinypilot/issues/1696

This PR allows for extra Playwright CLI options to passed to Playwright when running e2e tests.

2024-03-31 14:04 UTC, jdeanwallace commented
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1768)

⏳ @jotaen4tinypilot please review this Pull Request

2024-04-01 20:35 UTC, jdeanwallace reviewed
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1768)



<hr />

In: **dev-scripts/run-e2e-tests**:
Oh yeah, that makes sense. I was intrigued by the `--` idea, so did implement it here.

Can you check once again if all is in order?


<hr />

👀 @jotaen4tinypilot it's your turn please take a look

2024-04-01 22:13 UTC, mtlynch requested changes
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1768)



<hr />

In: **dev-scripts/run-e2e-tests**:
Neat!

<hr />

In: **dev-scripts/run-e2e-tests**:

```
> Line 88
npx playwright test "${PLAYWRIGHT_ARGS[@]+"${PLAYWRIGHT_ARGS[@]}"}"
```
This is some wacky bash!

Can we add a comment explaining what it's doing? I feel like nobody will understand it except for like the top 5% of bash developers.


<hr />

👀 @jdeanwallace, @jotaen4tinypilot it's your turn please take a look

2024-04-02 13:07 UTC, jdeanwallace reviewed
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1768)



<hr />

In: **dev-scripts/run-e2e-tests**:
Done.

<hr />

In: **dev-scripts/run-e2e-tests**:

```
> Line 49
      shift
```
Done.

<hr />

In: **dev-scripts/run-e2e-tests**:

```
> Line 93
npx playwright test "${PLAYWRIGHT_ARGS[@]+"${PLAYWRIGHT_ARGS[@]}"}"
```
> Can we add a comment explaining what it's doing? 

Done.

> Would it be safe to always pass on $PLAYWRIGHT_ARGS to npx ..., even if it’s empty? Or is there a scenario where Playwright might complain?

Yes, if `$PLAYWRIGHT_ARGS`is empty, nothing is passed to `npx`.


<hr />

👀 @mtlynch it's your turn please take a look

2024-04-02 13:13 UTC, merged