Fix About dialog e2e license link tests
tiny-pilot/tinypilot pull request #1806
Opened 2024-06-24 14:08 UTC by db39

2024-06-24 14:13 UTC, db39 commented
I'm not sure why, but using `await Promise.all` with `page.goto` didn't work. I didn't dig too deep into why, but I think it's to do with async calls. Instead I swapped to a for loop to synchronously perform the `goto` which works.

2024-06-24 14:21 UTC, db39 commented
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1806)

⏳ @jdeanwallace please review this Pull Request

2024-06-25 12:08 UTC, jdeanwallace requested changes
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1806)


⏳ Approval Pending (1 unresolved comments)
_Approval will be granted automatically when all comments are resolved_

<hr />

In: **e2e/about.spec.js**:

```
> Line 111
    for (const path of paths) {
```
My only concern is that we'll now be visiting each page in series (not in parallel). So if one page fails, it would end the test early without discovering other possible failures.

I've created a scratch PR that uses `Promise.all` with Playwright's `page.goto`:
* https://github.com/tiny-pilot/tinypilot/pull/1808

You're welcome to merge it yourself, if it's useful.


<hr />

👀 @db39 it's your turn please take a look

2024-06-25 12:59 UTC, db39 reviewed
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1806)



<hr />

In: **e2e/about.spec.js**:
Brilliant, thanks! I tested your version and it works the way we need it to. I've merged it into this branch.

2024-06-25 12:59 UTC, jdeanwallace approved these changes
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/tinypilot/1806)

Approved: I have approved this change on CodeApprove and all of my comments have been resolved.

2024-06-25 14:10 UTC, merged