Update Janus Docker container instructions
tiny-pilot/tinypilot pull request #938
Opened 2022-03-23 06:03 UTC by jdeanwallace

This PR updates the instructions on how to run the Janus Docker container on both a TinyPilot Voyager & TinyPilot Hobbyist device.

On a Voyager device, we need to specify that we're using a capture chip and change the uStreamer format to JPEG.

2022-03-23 17:35 UTC, jotaen4tinypilot approved these changes
Awesome, thanks, now the H264 stream works on my Voyager!

As an aside, is it expected (for now) that the colours look different via H264? Do you have that too?

![Screenshot 2022-03-23 at 18.15.14.png](https://files.reviewableusercontent.io/images/reviewable/83721279/SCGdjKkg7xYc5CVt8ekZKxE9/Screenshot%202022-03-23%20at%2018.15.14.png)

The colours should actually be:

![Screenshot 2022-03-23 at 18.22.25.png](https://files.reviewableusercontent.io/images/reviewable/83721279/J-QMyVkifQhDfamHe-fQIEWh/Screenshot%202022-03-23%20at%2018.22.25.png)

Also, just a curious find on the side, when accessing the conventional MJPEG endpoint (`/stream?advance_headers=1`) while Janus is hooked in, it streams this. I guess the plugin somehow scrambles uStreamers video memory internally.

![Screenshot 2022-03-23 at 18.20.32.png](https://files.reviewableusercontent.io/images/reviewable/83721279/aN5cRZLONYL2661ksovCZeO5/Screenshot%202022-03-23%20at%2018.20.32.png)

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tiny-pilot/tinypilot/938#-:-MyrleXgAMEOO094PE7t:b-f1r0ps)* status: 0 of 1 LGTMs obtained



<!-- Sent from Reviewable.io -->

2022-03-23 18:19 UTC, mtlynch requested changes
> *[Reviewable](https://reviewable.io/reviews/tiny-pilot/tinypilot/938)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[README.md, line 103 at r1](https://reviewable.io/reviews/tiny-pilot/tinypilot/938#-Myrxz9X5RJ_DHGfMQ6V:-Myrxz9X5RJ_DHGfMQ6W:b-z2jcwp) ([raw file](https://github.com/tiny-pilot/tinypilot/blob/b40dc3691d64a8ba1b9ac5656b52137b9a8cf439/README.md#L103)):*
> ```Markdown
>   (sudo useradd --create-home --system --user-group tinypilot || true) && \
>   echo 'ustreamer_capture_device: tc358743' | sudo tee "${TINYPILOT_SETTINGS}" && \
>   echo 'ustreamer_format: jpeg' | sudo tee --append "${TINYPILOT_SETTINGS}" && \
> ```

I think @jotaen4tinypilot is seeing distorted colors because of this line. Voyager [uses `uyvy` format](https://github.com/tiny-pilot/tinypilot/blob/0e761196307b2aa393972b694ab923f624f86be2/quick-install#L70). If we set just `ustreamer_capture_device: tc358743`, then `quick-install` should auto-infer the remaining Voyager settings.

I just tried an install deleting the `ustreamer_format` line and everything works correctly:

![image.png](https://files.reviewableusercontent.io/images/reviewable/7783288/AmFFdmJAtsHgtg10yw9MyKDM/image.png)


<!-- Sent from Reviewable.io -->

2022-03-23 18:30 UTC, jotaen4tinypilot commented
👍 I can confirm the fix that @mtlynch suggested, which also fixed the MJPEG stream (so no funky memory scrambling after all).

2022-03-24 01:46 UTC, jdeanwallace reviewed
> *[Reviewable](https://reviewable.io/reviews/tiny-pilot/tinypilot/938)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[README.md, line 103 at r1](https://reviewable.io/reviews/tiny-pilot/tinypilot/938#-Myrxz9X5RJ_DHGfMQ6V:-Myta3IFBvqi2ibWbaI5:b-p7clck) ([raw file](https://github.com/tiny-pilot/tinypilot/blob/b40dc3691d64a8ba1b9ac5656b52137b9a8cf439/README.md#L103)):*
<details><summary><i>Previously, mtlynch (Michael Lynch) wrote…</i></summary><blockquote>

I think @jotaen4tinypilot is seeing distorted colors because of this line. Voyager [uses `uyvy` format](https://github.com/tiny-pilot/tinypilot/blob/0e761196307b2aa393972b694ab923f624f86be2/quick-install#L70). If we set just `ustreamer_capture_device: tc358743`, then `quick-install` should auto-infer the remaining Voyager settings.

I just tried an install deleting the `ustreamer_format` line and everything works correctly:

![image.png](https://files.reviewableusercontent.io/images/reviewable/7783288/AmFFdmJAtsHgtg10yw9MyKDM/image.png)

</blockquote></details>

Thanks! I've removed the incorrect `ustreamer_format` line from the instructions.


<!-- Sent from Reviewable.io -->

2022-03-24 01:50 UTC, merged